# Generated by Django 5.1.8 on 2025-07-02 10:06

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('extras', '0123_journalentry_kind_default'),
        ('tenancy', '0017_natural_ordering'),
        ('virtualization', '0048_populate_mac_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('status', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('url', models.URLField(max_length=300)),
                ('version', models.CharField(max_length=200)),
                ('cluster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars_cluster', to='virtualization.cluster')),
                ('cluster_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars_cluster_group', to='virtualization.clustergroup')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars_device', to='dcim.device')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars_manufacturer', to='dcim.manufacturer')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars_tenant', to='tenancy.tenant')),
                ('tenant_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars_tenant_group', to='tenancy.tenantgroup')),
                ('virtual_machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars_virtual_machine', to='virtualization.virtualmachine')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
    ]
