# Generated by Django 5.1.8 on 2025-07-02 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('netbox_cars', '0001_initial'),
        ('tenancy', '0017_natural_ordering'),
        ('virtualization', '0048_populate_mac_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars_cluster', to='virtualization.cluster'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='cluster_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars_cluster_group', to='virtualization.clustergroup'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars_device', to='dcim.device'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars_manufacturer', to='dcim.manufacturer'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars_tenant', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='tenant_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars_tenant_group', to='tenancy.tenantgroup'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='virtual_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars_virtual_machine', to='virtualization.virtualmachine'),
        ),
    ]
