# Generated by Django 5.1.8 on 2025-07-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_applications', '0006_alter_installedapplication_options_and_more'),
        ('netbox_cars', '0002_alter_cars_cluster_alter_cars_cluster_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='installedapplication',
            field=models.ManyToManyField(blank=True, related_name='certificate', to='adestis_netbox_applications.installedapplication'),
        ),
    ]
