# Generated by Django 5.2.5 on 2026-03-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_certificate_management', '0004_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='authority_identifier',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
