# Generated by Django 5.2.5 on 2026-03-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_certificate_management', '0005_alter_certificate_authority_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='subject_key_identifier',
            field=models.CharField(max_length=512),
        ),
    ]
