# Generated by Django 5.1.8 on 2026-05-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_certificate_management', '0006_alter_certificate_subject_key_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='subject_alternative_name',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
