# Generated by Django 5.1.8 on 2026-06-16 09:17

import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_certificate_management', '0007_alter_certificate_subject_alternative_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
    ]
