# Generated by Django 5.1.8 on 2025-07-03 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('netbox_certificate_management', '0001_initial'),
        ('tenancy', '0017_natural_ordering'),
        ('virtualization', '0048_populate_mac_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='url',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='version',
        ),
        migrations.AddField(
            model_name='certificate',
            name='authority_key_identifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authority_certificates', to='netbox_certificate_management.certificate'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate',
            field=models.CharField(default='', max_length=10000, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='contact',
            field=models.ManyToManyField(blank=True, related_name='certificate', to='tenancy.contact'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='contact_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='tenancy.contactgroup'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issuer',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='certificate',
            name='issuer_parent_certificate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_certificates', to='netbox_certificate_management.certificate'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='key_technology',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='certificate',
            name='predecessor_certificate',
            field=models.ManyToManyField(blank=True, related_name='certificate', to='netbox_certificate_management.certificate'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='subject',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='certificate',
            name='subject_alternative_name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='subject_key_identifier',
            field=models.CharField(default='', max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='successor_certificates',
            field=models.ManyToManyField(blank=True, related_name='certificate', to='netbox_certificate_management.certificate'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='supplier_product',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='certificate',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='valid_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='cluster_group',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='device',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='virtual_machine',
        ),
        migrations.AddField(
            model_name='certificate',
            name='cluster',
            field=models.ManyToManyField(blank=True, related_name='certificate', to='virtualization.cluster'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='cluster_group',
            field=models.ManyToManyField(blank=True, related_name='certificate', to='virtualization.clustergroup'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='device',
            field=models.ManyToManyField(blank=True, related_name='certificate', to='dcim.device'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='virtual_machine',
            field=models.ManyToManyField(blank=True, related_name='certificate', to='virtualization.virtualmachine'),
        ),
    ]
